version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sepa_brl_db
      POSTGRES_USER: sepa_user
      POSTGRES_PASSWORD: sepa_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sepa_user -d sepa_brl_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sepa_user:sepa_password@db:5432/sepa_brl_db
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: